# Generated by Django 5.2.1 on 2025-06-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='nom',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='technologie',
            field=models.CharField(choices=[('2G', '2G'), ('3G', '3G'), ('4G', '4G')], db_index=True, max_length=3),
        ),
    ]
